#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"




# Launch the bar
launch_bar() {
	killall -q polybar

	# Wait until the processes have been shut down
	while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

	# Launch the bar
	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q top -c "$DIR"/dual.ini &
		MONITOR=$mon polybar -q bottom -c "$DIR"/dual.ini &
	done
}


launch_bar
